name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools twine wheel
        python -m pip install .[all]
        python setup.py --version
        git config --global --add user.name "Renku @ SDSC"
        git config --global --add user.email "renku@datascience.ch"
    - name: Test
      run: ./run-tests.sh

  test-distro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[all]
    - name: Build Package
      run: python setup.py sdist bdist_wheel
    - name: test with twine
      run: twine check dist/*
